New travis build scripts

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,43 +1,82 @@
-language: haskell
-env:
-- GHCVER=7.8.4
-- GHCVER=7.10.2
-- GHCVER=head
+# This Travis job script has been generated by a script via
+#
+#   make_travis_yml_2.hs 'elm-bridge.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
+language: c
+sudo: false
+
+git:
+  submodules: false  # whether to recursively clone submodules
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
 matrix:
-  allow_failures:
-  - env: GHCVER=head
+  include:
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.10.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.0.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.1"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.2.1], sources: [hvr-ghc]}}
+
 before_install:
-- |
-  if [ $GHCVER = `ghc --numeric-version` ]; then
-    travis/cabal-apt-install --enable-tests $MODE
-    export CABAL=cabal
-  else
-    travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-    travis_retry sudo apt-get update
-    travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy
-    export CABAL=cabal-1.22
-    export PATH=/opt/ghc/$GHCVER/bin:$PATH
-  fi
-- $CABAL update
-- |
-  if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.2" ]; then
-    $CABAL install happy alex
-    export PATH=$HOME/.cabal/bin:$PATH
-  fi
+ - HC=${CC}
+ - unset CC
+ - PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH
+ - PKGNAME='elm-bridge'
+
 install:
-- $CABAL install --dependencies-only --enable-tests
-- $CABAL configure -flib-Werror --enable-tests $MODE
+ - cabal --version
+ - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - BENCH=${BENCH---enable-benchmarks}
+ - TEST=${TEST---enable-tests}
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - rm -fv cabal.project.local
+ - "echo 'packages: .' > cabal.project"
+ - rm -f cabal.project.freeze
+ - cabal new-build -w ${HC} ${TEST} ${BENCH} --dep -j2 all
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --dep -j2 all
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-- ghc --numeric-version
-- $CABAL check
-- $CABAL build
-- $CABAL test --show-details=always
-deploy:
-  provider: hackage
-  username: AlexanderThiemann
-  skip_cleanup: true
-  on:
-    condition: "$GHCVER = 7.8.4"
-    tags: true
-  password:
-    secure: aeBH/I8w2COXJ+QeRdTcelEveteWNSOg6ir4uTuh1aFxquXpkfnsbmK8fexjnvZnSOJMaAcjadorGxPBtQfy1dycTnDtYrX2qhf/vXCVEsMy3faMzadfMLg9iXaMvwUiaBeOT/NlG8T4BggQlQdEPwZUG/gWduYqLwM7ykHPmmkqQWX+8vDw5Sya+oS2Qe9InFPejTNjYX8ZYVJdII0kpYt5mYu9PvbYbDO+2CE9w+YW5D0nJ6VgWHPsdWQiqAS9/3uCPdPC0fzCjdCrCgA5ECxdATuIOFl3jZnQcV3cNZEWpsbxt4OBstj8zPmyc3SrFr0lxFf9oSYqVo4o6zDEO7Y0zBcc3i+a2hMmDVhvUhTaWCop3cLtuNTLHo96usAtALfG/XL0QPhBVhG8OL8aBu40px1As/tINvwThHZxyJ7t1GVgtTb9ZoKd9VQna5avlLevHGUyM8vYhZieTZO4drtaGZlXJsuJ4dzFt3evLbqMgm7piM1w0ZRsJfaJrQasqKDg/p9aPu6b0itCjIR8oZl4JRs8E5HutDeRrkY/Y3lw3F57MpSHvIwtc102QvWTqB+YeIMuVd9AEMANV9ZXO8V9PN8DXeCmFuN1Ck21UI0y0gz4T52NOInLHb0tizgIvjK8afL28PHWRyv+61T09uhQOGBSvm81+xn34K4Noc0=
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - rm -rf .ghc.environment.* dist/
+ - cabal sdist # test that a source-distribution can be generated
+ - cd dist/
+ - SRCTAR=(${PKGNAME}-*.tar.gz)
+ - SRC_BASENAME="${SRCTAR/%.tar.gz}"
+ - tar -xvf "./$SRC_BASENAME.tar.gz"
+ - cd "$SRC_BASENAME/"
+## from here on, CWD is inside the extracted source-tarball
+ - rm -fv cabal.project.local
+ - "echo 'packages: .' > cabal.project"
+ # this builds all libraries and executables (without tests/benchmarks)
+ - rm -f cabal.project.freeze
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+ # this builds all libraries and executables (including tests/benchmarks)
+ # - rm -rf ./dist-newstyle
+
+ # build & run tests
+ - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+ - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} all; fi
+
+# EOF
